name: testapp
mode: qa

logger: &default_logger
  output: /log/
  filename: testapp
  ext: .log
  level: debug
section:
  dev:
    id: 1
    mysql:
      addr: localhost
      port: 3306
    redis:
      addr: localhost
      port: 6379