// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package pbs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BaseOutput struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseOutput) Reset()         { *m = BaseOutput{} }
func (m *BaseOutput) String() string { return proto.CompactTextString(m) }
func (*BaseOutput) ProtoMessage()    {}
func (*BaseOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *BaseOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseOutput.Unmarshal(m, b)
}
func (m *BaseOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseOutput.Marshal(b, m, deterministic)
}
func (m *BaseOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseOutput.Merge(m, src)
}
func (m *BaseOutput) XXX_Size() int {
	return xxx_messageInfo_BaseOutput.Size(m)
}
func (m *BaseOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseOutput.DiscardUnknown(m)
}

var xxx_messageInfo_BaseOutput proto.InternalMessageInfo

func (m *BaseOutput) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *BaseOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*BaseOutput)(nil), "mpc.BaseOutput")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 99 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x48, 0x56, 0xb2, 0xe2,
	0xe2, 0x72, 0x4a, 0x2c, 0x4e, 0xf5, 0x2f, 0x2d, 0x29, 0x28, 0x2d, 0x11, 0x12, 0xe2, 0x62, 0x49,
	0xce, 0x4f, 0x49, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x02, 0xb3, 0x85, 0x24, 0xb8, 0xd8,
	0x73, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0x60, 0xdc,
	0x24, 0x36, 0xb0, 0x39, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x87, 0xa9, 0xa5, 0x71, 0x57,
	0x00, 0x00, 0x00,
}
