// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mpc.proto

package pbs

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AnimalType int32

const (
	AnimalType_Dog AnimalType = 0
	AnimalType_Cat AnimalType = 1
	AnimalType_Pig AnimalType = 2
)

var AnimalType_name = map[int32]string{
	0: "Dog",
	1: "Cat",
	2: "Pig",
}

var AnimalType_value = map[string]int32{
	"Dog": 0,
	"Cat": 1,
	"Pig": 2,
}

func (x AnimalType) String() string {
	return proto.EnumName(AnimalType_name, int32(x))
}

func (AnimalType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_44bfd94b5d9503dc, []int{0}
}

type GetPetInput struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPetInput) Reset()         { *m = GetPetInput{} }
func (m *GetPetInput) String() string { return proto.CompactTextString(m) }
func (*GetPetInput) ProtoMessage()    {}
func (*GetPetInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_44bfd94b5d9503dc, []int{0}
}

func (m *GetPetInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPetInput.Unmarshal(m, b)
}
func (m *GetPetInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPetInput.Marshal(b, m, deterministic)
}
func (m *GetPetInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPetInput.Merge(m, src)
}
func (m *GetPetInput) XXX_Size() int {
	return xxx_messageInfo_GetPetInput.Size(m)
}
func (m *GetPetInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPetInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetPetInput proto.InternalMessageInfo

func (m *GetPetInput) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetPetOutput struct {
	Base                 *BaseOutput          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Animal               map[int64]AnimalType `protobuf:"bytes,2,rep,name=animal,proto3" json:"animal,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=mpc.AnimalType"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetPetOutput) Reset()         { *m = GetPetOutput{} }
func (m *GetPetOutput) String() string { return proto.CompactTextString(m) }
func (*GetPetOutput) ProtoMessage()    {}
func (*GetPetOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_44bfd94b5d9503dc, []int{1}
}

func (m *GetPetOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPetOutput.Unmarshal(m, b)
}
func (m *GetPetOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPetOutput.Marshal(b, m, deterministic)
}
func (m *GetPetOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPetOutput.Merge(m, src)
}
func (m *GetPetOutput) XXX_Size() int {
	return xxx_messageInfo_GetPetOutput.Size(m)
}
func (m *GetPetOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPetOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetPetOutput proto.InternalMessageInfo

func (m *GetPetOutput) GetBase() *BaseOutput {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *GetPetOutput) GetAnimal() map[int64]AnimalType {
	if m != nil {
		return m.Animal
	}
	return nil
}

type SetPetInput struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AnimalId             int64    `protobuf:"varint,2,opt,name=animal_id,json=animalId,proto3" json:"animal_id,omitempty"`
	AnimalType           string   `protobuf:"bytes,3,opt,name=animal_type,json=animalType,proto3" json:"animal_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPetInput) Reset()         { *m = SetPetInput{} }
func (m *SetPetInput) String() string { return proto.CompactTextString(m) }
func (*SetPetInput) ProtoMessage()    {}
func (*SetPetInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_44bfd94b5d9503dc, []int{2}
}

func (m *SetPetInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPetInput.Unmarshal(m, b)
}
func (m *SetPetInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPetInput.Marshal(b, m, deterministic)
}
func (m *SetPetInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPetInput.Merge(m, src)
}
func (m *SetPetInput) XXX_Size() int {
	return xxx_messageInfo_SetPetInput.Size(m)
}
func (m *SetPetInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPetInput.DiscardUnknown(m)
}

var xxx_messageInfo_SetPetInput proto.InternalMessageInfo

func (m *SetPetInput) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SetPetInput) GetAnimalId() int64 {
	if m != nil {
		return m.AnimalId
	}
	return 0
}

func (m *SetPetInput) GetAnimalType() string {
	if m != nil {
		return m.AnimalType
	}
	return ""
}

type SetPetOutput struct {
	Base                 *BaseOutput `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SetPetOutput) Reset()         { *m = SetPetOutput{} }
func (m *SetPetOutput) String() string { return proto.CompactTextString(m) }
func (*SetPetOutput) ProtoMessage()    {}
func (*SetPetOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_44bfd94b5d9503dc, []int{3}
}

func (m *SetPetOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPetOutput.Unmarshal(m, b)
}
func (m *SetPetOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPetOutput.Marshal(b, m, deterministic)
}
func (m *SetPetOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPetOutput.Merge(m, src)
}
func (m *SetPetOutput) XXX_Size() int {
	return xxx_messageInfo_SetPetOutput.Size(m)
}
func (m *SetPetOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPetOutput.DiscardUnknown(m)
}

var xxx_messageInfo_SetPetOutput proto.InternalMessageInfo

func (m *SetPetOutput) GetBase() *BaseOutput {
	if m != nil {
		return m.Base
	}
	return nil
}

func init() {
	proto.RegisterEnum("mpc.AnimalType", AnimalType_name, AnimalType_value)
	proto.RegisterType((*GetPetInput)(nil), "mpc.GetPetInput")
	proto.RegisterType((*GetPetOutput)(nil), "mpc.GetPetOutput")
	proto.RegisterMapType((map[int64]AnimalType)(nil), "mpc.GetPetOutput.AnimalEntry")
	proto.RegisterType((*SetPetInput)(nil), "mpc.SetPetInput")
	proto.RegisterType((*SetPetOutput)(nil), "mpc.SetPetOutput")
}

func init() { proto.RegisterFile("mpc.proto", fileDescriptor_44bfd94b5d9503dc) }

var fileDescriptor_44bfd94b5d9503dc = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x41, 0x4b, 0xfb, 0x30,
	0x18, 0xc6, 0x97, 0xe6, 0xbf, 0xee, 0xbf, 0x37, 0x43, 0x6b, 0x2e, 0x96, 0x89, 0x58, 0x2a, 0x6a,
	0xf1, 0x30, 0x61, 0x43, 0x10, 0x6f, 0x4e, 0x45, 0xe6, 0xc5, 0xd1, 0x7a, 0xf2, 0x22, 0xd9, 0x1a,
	0x4a, 0x71, 0x6d, 0x43, 0x9b, 0x0a, 0xfd, 0x62, 0x7e, 0x3e, 0x49, 0x52, 0xb4, 0xb2, 0x8b, 0xde,
	0xde, 0xbe, 0xbf, 0xe7, 0xe9, 0x93, 0x3c, 0x04, 0x86, 0x99, 0x58, 0x4f, 0x44, 0x59, 0xc8, 0x82,
	0xe2, 0x4c, 0xac, 0xc7, 0xa3, 0x75, 0x91, 0x65, 0x45, 0x6e, 0x56, 0xfe, 0x29, 0x90, 0x07, 0x2e,
	0x97, 0x5c, 0x2e, 0x72, 0x51, 0x4b, 0xba, 0x0f, 0x83, 0xba, 0xe2, 0xe5, 0x6b, 0x1a, 0xbb, 0xc8,
	0x43, 0x01, 0x0e, 0x6d, 0xf5, 0xb9, 0x88, 0xfd, 0x0f, 0x04, 0x23, 0x23, 0x7c, 0xaa, 0xa5, 0x52,
	0x1e, 0xc3, 0xbf, 0x15, 0xab, 0xb8, 0x96, 0x91, 0xe9, 0xee, 0x44, 0xa5, 0xcc, 0x59, 0xc5, 0x0d,
	0x0e, 0x35, 0xa4, 0x97, 0x60, 0xb3, 0x3c, 0xcd, 0xd8, 0xc6, 0xb5, 0x3c, 0x1c, 0x90, 0xe9, 0xa1,
	0x96, 0x75, 0xff, 0x33, 0xb9, 0xd1, 0xfc, 0x3e, 0x97, 0x65, 0x13, 0xb6, 0xe2, 0xf1, 0x23, 0x90,
	0xce, 0x9a, 0x3a, 0x80, 0xdf, 0x78, 0xd3, 0x1e, 0x48, 0x8d, 0xf4, 0x04, 0xfa, 0xef, 0x6c, 0x53,
	0x73, 0xd7, 0xf2, 0x50, 0xb0, 0xd3, 0xa6, 0x1b, 0xcb, 0x73, 0x23, 0x78, 0x68, 0xe8, 0xb5, 0x75,
	0x85, 0xfc, 0x18, 0x48, 0xf4, 0x8b, 0x0b, 0xd2, 0x03, 0x18, 0x9a, 0x74, 0x85, 0x2c, 0x8d, 0xfe,
	0x9b, 0xc5, 0x22, 0xa6, 0x47, 0x40, 0x5a, 0x28, 0x1b, 0xc1, 0x5d, 0xec, 0xa1, 0x60, 0x18, 0x02,
	0xfb, 0x0a, 0xf4, 0x67, 0x30, 0x8a, 0xfe, 0xda, 0xce, 0xf9, 0x19, 0xc0, 0xf7, 0x99, 0xe9, 0x00,
	0xf0, 0x5d, 0x91, 0x38, 0x3d, 0x35, 0xdc, 0x32, 0xe9, 0x20, 0x35, 0x2c, 0xd3, 0xc4, 0xb1, 0xa6,
	0x09, 0xe0, 0x25, 0x97, 0xf4, 0x02, 0x6c, 0x53, 0x1d, 0x75, 0x3a, 0x3d, 0xea, 0x7b, 0x8d, 0xf7,
	0xb6, 0x9a, 0xf5, 0x7b, 0xca, 0x10, 0x75, 0x0d, 0xd1, 0x96, 0x21, 0xfa, 0x61, 0x98, 0xf7, 0x5f,
	0xb0, 0x58, 0x55, 0x2b, 0x5b, 0xbf, 0x8d, 0xd9, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x84, 0x41,
	0x23, 0xa2, 0x3b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PetClient is the client API for Pet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PetClient interface {
	GetPet(ctx context.Context, in *GetPetInput, opts ...grpc.CallOption) (*GetPetOutput, error)
	SetPet(ctx context.Context, in *SetPetInput, opts ...grpc.CallOption) (*SetPetOutput, error)
}

type petClient struct {
	cc *grpc.ClientConn
}

func NewPetClient(cc *grpc.ClientConn) PetClient {
	return &petClient{cc}
}

func (c *petClient) GetPet(ctx context.Context, in *GetPetInput, opts ...grpc.CallOption) (*GetPetOutput, error) {
	out := new(GetPetOutput)
	err := c.cc.Invoke(ctx, "/mpc.Pet/GetPet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *petClient) SetPet(ctx context.Context, in *SetPetInput, opts ...grpc.CallOption) (*SetPetOutput, error) {
	out := new(SetPetOutput)
	err := c.cc.Invoke(ctx, "/mpc.Pet/SetPet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PetServer is the server API for Pet service.
type PetServer interface {
	GetPet(context.Context, *GetPetInput) (*GetPetOutput, error)
	SetPet(context.Context, *SetPetInput) (*SetPetOutput, error)
}

// UnimplementedPetServer can be embedded to have forward compatible implementations.
type UnimplementedPetServer struct {
}

func (*UnimplementedPetServer) GetPet(ctx context.Context, req *GetPetInput) (*GetPetOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPet not implemented")
}
func (*UnimplementedPetServer) SetPet(ctx context.Context, req *SetPetInput) (*SetPetOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPet not implemented")
}

func RegisterPetServer(s *grpc.Server, srv PetServer) {
	s.RegisterService(&_Pet_serviceDesc, srv)
}

func _Pet_GetPet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPetInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PetServer).GetPet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mpc.Pet/GetPet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PetServer).GetPet(ctx, req.(*GetPetInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pet_SetPet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPetInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PetServer).SetPet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mpc.Pet/SetPet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PetServer).SetPet(ctx, req.(*SetPetInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mpc.Pet",
	HandlerType: (*PetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPet",
			Handler:    _Pet_GetPet_Handler,
		},
		{
			MethodName: "SetPet",
			Handler:    _Pet_SetPet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mpc.proto",
}
